# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wv_value <- function(x, wv, filter_number) {
    .Call(`_DaubechiesSim_wv_value`, x, wv, filter_number)
}

wv_values <- function(X, wv, filter_number) {
    .Call(`_DaubechiesSim_wv_values`, X, wv, filter_number)
}

wvs_dilation_shift <- function(X, wv, filter_number, j, k) {
    .Call(`_DaubechiesSim_wvs_dilation_shift`, X, wv, filter_number, j, k)
}

wv_dilation_shift <- function(x, wv, filter_number, j, k) {
    .Call(`_DaubechiesSim_wv_dilation_shift`, x, wv, filter_number, j, k)
}

wv_trans_fast <- function(X, wv, filter_number, R, gammas, beta) {
    .Call(`_DaubechiesSim_wv_trans_fast`, X, wv, filter_number, R, gammas, beta)
}

wv_trans <- function(X, wv, filter_number, R, gammas, beta) {
    .Call(`_DaubechiesSim_wv_trans`, X, wv, filter_number, R, gammas, beta)
}

wv_analysis <- function(X, wv, filter_number, level, ks) {
    .Call(`_DaubechiesSim_wv_analysis`, X, wv, filter_number, level, ks)
}

outer_prod <- function(X, X_space_g_density, wv, filter_number, level, ks, res, norm_const) {
    .Call(`_DaubechiesSim_outer_prod`, X, X_space_g_density, wv, filter_number, level, ks, res, norm_const)
}

generate_cov <- function(X, X_space_g_density, wv, filter_number, level, ks, res, norm_const) {
    .Call(`_DaubechiesSim_generate_cov`, X, X_space_g_density, wv, filter_number, level, ks, res, norm_const)
}

rcpparma_hello_world <- function() {
    .Call(`_DaubechiesSim_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_DaubechiesSim_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_DaubechiesSim_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_DaubechiesSim_rcpparma_bothproducts`, x)
}

